[package]
name = "bevy-2d-renderer"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
bevy = "0.14"
bevy_ecs_tilemap = "0.14"
bevy_trickfilm = "0.7"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
